---
title: "R Notebook"
output: html_notebook

---

1. Vectores y Matrices
```{r}
student_1<- c(50.4,62.3,92.1,77.6, TRUE)
student_2<- c(41.7,87.9,75.3,72.4, FALSE)
student_3<- c(30.3,67.8,69.3,71.2, FALSE)
student_4<- c(65.4,85.1,92.3,96.8, TRUE)
student_5<- c(70.4,88.2,95.2,90.7, TRUE)

students_vector<- c(student_1,student_2,student_3, student_4, student_5)

students_matrix<- matrix(students_vector, byrow=TRUE, nrow=5)
```
2.Nombrado de una matriz
```{r}
name_students<- c("Lily Brown", "Davis Moore", "Susan Taylor", "Mike Jones", "Tom Hill")
name_courses_legal_age<- c("TIC","Accounting", "Psychology", "Ethics", "Legal_Age")
colnames(students_matrix)<- name_courses_legal_age
row.names(students_matrix)<- name_students

students_matrix
```
3. rowSums, cbind

```{r}
total_grade_student<-rowSums(students_matrix [,1:4])
result_students<- cbind(students_matrix,total_grade_student)
```

4. Selecionando elementos de una matriz
```{r}
selected_elements<- result_students[c((1,3,5),(2,4))]
```

Data Frames
```{r}
library(tidyverse)
students_grades_df<- data.frame(result_students)
students_grades_df %>% filter(Accounting > 80, Legal_Age==1)
```

6. Funciones, condiciones y Bucles

```{r}
interpret <- function(Scores){
  if(Scores<= 45){
    print("Student at risk")
    return(Scores)
  }
  else if (Scores> 45 & Scores<61) {
    print("Student may be approved")
    return(Scores)
  }else if(Scores> 61){
    print("Student approved")
    return(Scores)
  }
}

interpret(result_students[1,1])

students_projection <- function(result_students){
  for (row in 1:4) {
    for (col in 1:ncol(result_students)) {
      interpret(result_students[row,col])
      }  
    }
}

students_projection(result_students)

```

